### ISSUE TITLE
main.ts (11,36): Cannot find module 'log4ts'. (2307)

### ISSUE THREAD

**Issue by zhhigh** [xinbenlv/haoshiyou-bot#5]
Starting Wechaty v0.8.133 with Node.js v7.10.1 ...
Working directory: /bot
Executing ts-node main.ts

/wechaty/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
main.ts (11,36): Cannot find module 'log4ts'. (2307)
main.ts (14,29): Cannot find module 'log4ts/build/appenders/ConsoleAppender'. (2307)
main.ts (15,25): Cannot find module 'log4ts/build/layouts/BasicLayout'. (2307)
main.ts (16,24): Cannot find module 'log4ts/build/LogLevel'. (2307)
    at getOutput (/wechaty/node_modules/ts-node/src/index.ts:307:15)
    at /wechaty/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/wechaty/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/wechaty/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/wechaty/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)

**Comment by xinbenlv** [comment]
Migrated to haoshiyou-2026. See https://github.com/haoshiyou/haoshiyou-2026/issues/51
